#EXAMPLE OF LABELS

kind: Pod
apiVersion: v1
metadata:
  name: testpod
  labels:                                                   
    env: development
    class: pods
spec:
    containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Test-App; sleep 5 ; done"]
         
#NODE SELECTOR EXAMPLE

kind: Pod
apiVersion: v1
metadata:
  name: nodelabels
  labels:
    env: development
spec:
    containers:
       - name: c00
         image: ubuntu
         command: ["/bin/bash", "-c", "while true; do echo Demo-App; sleep 5 ; done"]
    nodeSelector:                                         
       hardware: t2-medium
