# Config Map 
 
# Step 1: Create A Sample Configuration file save it . 

# Step 2: Run Command "kubectl create configmap <nameofmap> --from-file=<pathoffile/filename>"

# Step 3: Run Command "kubectl get configmap"

# Using Volume 

apiVersion: v1
kind: Pod
metadata:
  name: myvolconfig
spec:
  containers:
  - name: c1
    image: centos
    command: ["/bin/bash", "-c", "while true; do echo Test-App; sleep 10 ; done"]
    volumeMounts:
      - name: testconfigmap
        mountPath: "/tmp/data/config"   # the config files will be mounted as ReadOnly by default here
  volumes:
  - name: testconfigmap
    configMap:
       name: mymap   # this should match the config map name created in the first step
       items:
       - key: sample.conf
         path: ./sample.conf

# Using Env 

apiVersion: v1
kind: Pod
metadata:
        name: deploy-env
spec:
        containers:
                - name: c01
                  image: centos
                  command: ["/bin/bash","-c","while true; do echo Test-App; sleep 5; done"]
                  env:
                   - name: MyEnv
                     valueFrom:
                             configMapKeyRef:
                              name: mymap
                              key: sample.conf
